package com.persys.osmanager.resource;

import java.util.Locale;
import java.util.ResourceBundle;

import br.com.model.interfaces.IEquipamento;

import com.persys.osmanager.componente.ComponenteFactory;
import com.persys.osmanager.componente.helper.AttrDim;
import com.persys.osmanager.componente.interfaces.IForm;
import com.persys.osmanager.data.AppData;
import com.persys.osmanager.exception.ViewException;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.event.ShortcutAction.ModifierKey;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

/**
 * @author ricardosabatine, jpmorijo
 * @version 1.0.0
 * @since 18/02/2013 Form Para Equipamento
 */

public class EquipamentoForm extends CustomComponent implements IForm<IEquipamento>{

	private final static ResourceBundle bundle;
	static{
		 bundle = ResourceBundle.getBundle("com/persys/frontend/equipment",Locale.getDefault());
	}	private static final long serialVersionUID = 1L;

	private VerticalLayout mainLayout;
	private TextArea textFieldDescricao;
	private TextField textFieldMarca;
	private TextField textFieldCodigoBarra;
	private TextField textFieldNome;
	private TextField textFieldNumeroSerie;
	private ComboBox comboBoxStatus;
	private TextField textFieldModelo;
	private TextField textFieldCodigo;

	private final ComponenteFactory componenteFactory = new ComponenteFactory();
	private IEquipamento equipamento;
	
	public EquipamentoForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		mainLayout.addComponent(buildHorizontalLayout_1());

		// textFieldNome
		textFieldNome = componenteFactory.createTextFieldRequiredError(new TextField(), bundle.getString("equipmentname"), bundle.getString("equipmentnameinvalid"),
				AttrDim.FORM_COM_SINGLE_WIDTH);
		textFieldNome.setMaxLength(150);
		textFieldNome.addShortcutListener(
		        new AbstractField.FocusShortcut(textFieldNome, KeyCode.ENTER,
		                                        ModifierKey.SHIFT));
		textFieldNome.focus();
		
		mainLayout.addComponent(textFieldNome);

		mainLayout.addComponent(buildHorizontalLayout());
		mainLayout.addComponent(buildHorizontalLayoutNumeroSerie());

		
		// textFieldNome
		textFieldDescricao = new TextArea();
		textFieldDescricao.setCaption(bundle.getString("description"));
		textFieldDescricao.setImmediate(false);
		textFieldDescricao.setWidth(AttrDim.FORM_COM_SINGLE_WIDTH);
		textFieldDescricao.setMaxLength(255);
		textFieldDescricao.setHeight("-1px");
		mainLayout.addComponent(textFieldDescricao);

		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout() {
		// common part: create layout
		HorizontalLayout horizontalLayout = new HorizontalLayout();
		horizontalLayout.setImmediate(false);
		horizontalLayout.setWidth("-1px");
		horizontalLayout.setHeight("-1px");
		horizontalLayout.setSpacing(true);

		// textFieldCodigoBarra
		textFieldCodigoBarra = new TextField();
		textFieldCodigoBarra.setCaption(bundle.getString("barcode"));
		textFieldCodigoBarra.setImmediate(false);
		textFieldCodigoBarra.setWidth(AttrDim.FORM_COM_DOUBLE_WIDTH);
		textFieldCodigoBarra.setMaxLength(100);
		textFieldCodigoBarra.setHeight("-1px");
		horizontalLayout.addComponent(textFieldCodigoBarra);

		// textFieldNome
		textFieldNumeroSerie = componenteFactory.createTextFieldRequiredError(new TextField(), bundle.getString("serialnumber"), bundle.getString("serialnumberinvalid"),
				AttrDim.FORM_COM_DOUBLE_WIDTH);
		mainLayout.addComponent(textFieldNumeroSerie);
		textFieldNumeroSerie.setMaxLength(200);
		horizontalLayout.addComponent(textFieldNumeroSerie);

		return horizontalLayout;
	}

	@SuppressWarnings("deprecation")
	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		HorizontalLayout horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);

		// textFieldCodigo
		textFieldCodigo = new TextField();
		textFieldCodigo.setCaption(bundle.getString("code"));
		textFieldCodigo.setImmediate(false);
		textFieldCodigo.setWidth(AttrDim.FORM_COM_DOUBLE_WIDTH);
		textFieldCodigo.setMaxLength(100);
		textFieldCodigo.setHeight("-1px");
		horizontalLayout_1.addComponent(textFieldCodigo);

		// comboBoxStatus
		comboBoxStatus = new ComboBox();
		comboBoxStatus.setCaption(bundle.getString("situation"));
		comboBoxStatus.setImmediate(false);
		comboBoxStatus.setWidth(AttrDim.FORM_COM_DOUBLE_WIDTH);
		comboBoxStatus.setHeight("-1px");
		comboBoxStatus.setContainerDataSource(AppData.listStatusInteger());
		comboBoxStatus.setItemCaptionMode(ComboBox.ITEM_CAPTION_MODE_PROPERTY);
		comboBoxStatus.setItemCaptionPropertyId("statusNome");
		comboBoxStatus.setNullSelectionAllowed(false);
		horizontalLayout_1.addComponent(comboBoxStatus);

		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayoutNumeroSerie() {
		// common part: create layout
		HorizontalLayout horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);

		// textFieldMarca
		textFieldMarca = new TextField();
		textFieldMarca.setCaption(bundle.getString("brand"));
		textFieldMarca.setImmediate(false);
		textFieldMarca.setWidth(AttrDim.FORM_COM_DOUBLE_WIDTH);
		textFieldMarca.setMaxLength(100);
		textFieldMarca.setHeight("-1px");
		horizontalLayout_1.addComponent(textFieldMarca);

		// textFieldCodigo
		textFieldModelo = new TextField();
		textFieldModelo.setCaption(bundle.getString("model"));
		textFieldModelo.setImmediate(false);
		textFieldModelo.setWidth(AttrDim.FORM_COM_DOUBLE_WIDTH);
		textFieldModelo.setMaxLength(150);
		textFieldModelo.setHeight("-1px");
		horizontalLayout_1.addComponent(textFieldModelo);
		
		return horizontalLayout_1;
	}


	@Override
	public IEquipamento commit() throws ViewException {
		try{
			textFieldNome.validate();
			equipamento.setCodigo(textFieldCodigo.getValue());
    		equipamento.setEtiqueta(textFieldCodigoBarra.getValue());
			equipamento.setMarca(textFieldMarca.getValue());
			equipamento.setEquipamento(textFieldNome.getValue());
			equipamento.setNumeroSerie(textFieldNumeroSerie.getValue());
			equipamento.setDescricao(textFieldDescricao.getValue());
			equipamento.setStatusModel((Integer)comboBoxStatus.getValue());
			equipamento.setModelo(textFieldModelo.getValue());
			return equipamento;
		}catch (Exception e) {
			throw new ViewException(e.getMessage());
		}
	}

	@Override
	public void initData(IEquipamento data) {

		textFieldCodigo.setReadOnly(false);

		textFieldCodigo.setValue(data.getCodigo());
		textFieldCodigoBarra.setValue(data.getEtiqueta());
		textFieldDescricao.setValue(data.getDescricao());
		textFieldMarca.setValue(data.getMarca());
		textFieldNome.setValue(data.getEquipamento());
		textFieldNumeroSerie.setValue(data.getNumeroSerie());
		textFieldModelo.setValue(data.getModelo());
		comboBoxStatus.select(data.getStatusModel());

		equipamento = data;

	}

	@Override
	public void modoView() {
		textFieldCodigo.setReadOnly(true);
	}

	@Override
	public void modoAdd() {
		textFieldCodigo.setReadOnly(true);
	}
		

}
