package com.persys.osmanager.organization;

import java.util.Locale;
import java.util.ResourceBundle;
import org.vaadin.csvalidation.CSValidator;
import br.com.model.interfaces.IOrganizacao;
import com.persys.osmanager.componente.ComponenteFactory;
import com.persys.osmanager.componente.PreconditionsView;
import com.persys.osmanager.componente.helper.AttrDim;
import com.persys.osmanager.componente.interfaces.IForm;
import com.persys.osmanager.exception.ViewException;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class OrganizationForm extends CustomComponent implements IForm<IOrganizacao> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VerticalLayout mainLayout;
	
	private TextField textFieldTelefone;
	private TextField textFieldEmail;
	private TextField textFieldInscricaoEstadual;
	private TextField textFieldCnpj;
	private TextField textFieldNomeFantasia;
	private TextField textFieldRazaoSocial;
	private final static ResourceBundle bundle;
	private final ComponenteFactory componenteFactory = new ComponenteFactory();
	private static String errorMessage;
   
	static{
		 bundle = ResourceBundle.getBundle("com/persys/frontend/organization",Locale.getDefault());
		 errorMessage = bundle.getString("requirederror");
	}
	
	private IOrganizacao organizacao;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public OrganizationForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		setWidth(AttrDim.FORM_WIDTH);
		setHeight(AttrDim.FORM_HEIGHT);
		
		
		// textFieldRazaoSocial
		textFieldRazaoSocial = componenteFactory.createTextFieldRequiredError(new TextField(), bundle.getString("name"), errorMessage, AttrDim.FORM_COM_SINGLE_WIDTH);
		
		mainLayout.addComponent(textFieldRazaoSocial);
		
		// textFieldNomeFantasia
		textFieldNomeFantasia = componenteFactory.createTextFieldRequiredError(new TextField(), bundle.getString("namefan"), errorMessage, AttrDim.FORM_COM_SINGLE_WIDTH);
		mainLayout.addComponent(textFieldNomeFantasia);
		
		mainLayout.addComponent(buildHorizontalLayoutCnpjIE());
		
		// textFieldEmail
		textFieldEmail = componenteFactory.createTextFieldRequiredError(new TextField(), bundle.getString("email"), errorMessage, AttrDim.FORM_COM_SINGLE_WIDTH);
		CSValidator validator = new CSValidator();
		validator.extend(textFieldEmail);
		validator.setRegExp(PreconditionsView.EMAIL_PATTERN);
		validator.setErrorMessage(textFieldEmail.getCaption()+ ":" +errorMessage);
		mainLayout.addComponent(textFieldEmail);
		
		textFieldTelefone = componenteFactory.createTextFieldRequiredError(new TextField(), bundle.getString("phone"), errorMessage);
		mainLayout.addComponent(textFieldTelefone);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayoutCnpjIE() {
		// common part: create layout
		HorizontalLayout horizontalLayoutCnpjIE = new HorizontalLayout();
		horizontalLayoutCnpjIE.setImmediate(false);
		horizontalLayoutCnpjIE.setWidth("-1px");
		horizontalLayoutCnpjIE.setHeight("-1px");
		horizontalLayoutCnpjIE.setMargin(false);
		horizontalLayoutCnpjIE.setSpacing(true);
		
		// textFieldCnpj
		textFieldCnpj = componenteFactory.createTextFieldRequiredError(new TextField(), bundle.getString("cnpj"), errorMessage);
		textFieldCnpj.setMaxLength(14);
		horizontalLayoutCnpjIE.addComponent(textFieldCnpj);
		
		// textFieldInscricaoEstadual
		textFieldInscricaoEstadual = componenteFactory.createTextField(new TextField(), bundle.getString("ie"));
		horizontalLayoutCnpjIE.addComponent(textFieldInscricaoEstadual);
		
		return horizontalLayoutCnpjIE;
	}
	
	@Override
	public IOrganizacao commit() throws ViewException {
		
		componenteFactory.valida();
		
		organizacao.setCnpj(textFieldCnpj.getValue());
		organizacao.setEmail(textFieldEmail.getValue());
		organizacao.setNomeFantasia(textFieldNomeFantasia.getValue());
		organizacao.setRazaoSocial(textFieldRazaoSocial.getValue());
		organizacao.setTelefone(textFieldTelefone.getValue());
		organizacao.setInscricaoEstadual(textFieldInscricaoEstadual.getValue());	
	
		return organizacao;
	}

	@Override
	public void initData(IOrganizacao data) {
		textFieldCnpj.setValue(data.getCnpj());
		textFieldEmail.setValue(data.getEmail());
		textFieldNomeFantasia.setValue(data.getNomeFantasia());
		textFieldRazaoSocial.setValue(data.getRazaoSocial());
		textFieldTelefone.setValue(data.getTelefone());
		textFieldInscricaoEstadual.setValue(data.getInscricaoEstadual());	
		organizacao = data;
	}

	@Override
	public void modoView() {}

	@Override
	public void modoAdd() {}
	
}
